#!/bin/sh
#
# /etc/init.d/teamcity -- startup script for the TeamCity server
#
# Written by João Rocha da Silva <https://github.com/silvae86>.
#
### BEGIN INIT INFO
# Provides:          teamcity
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start PROGRAM
# Description:       Start the PROGRAM search engine platform
### END INIT INFO

#./lib/lsb/init-functions

dendro_username='dendro'

#teamcity
teamcity_installation_path='/TeamCity'
teamcity_service_name='teamcity'
teamcity_startup_item_file='/etc/init.d/teamcity'
teamcity_log_file='/var/log/teamcity.log'
teamcity_pid_file='/TeamCity/service_pids/teamcity.pid'
teamcity_service_name='teamcity'

#su joaorocha "cd /Users/joaorocha/Desktop; /bin/bash -c "exec "echo $(pwd) >> /Users/joaorocha/Desktop/pwd.txt"  && exec "yes >> testes.txt > /dev/null 2>&1" & echo $! > /Users/joaorocha/Desktop/yes.pid""

start_service_command()
{
  # su joaorocha \
  # "cd /Users/joaorocha/Desktop; /bin/bash -c \
  # "exec "echo $(pwd) >> /Users/joaorocha/Desktop/pwd.txt"  &&
  # exec "yes >> testes.txt > /dev/null 2>&1" & echo $! > /Users/joaorocha/Desktop/yes.pid""

  if [ ! -f  $teamcity_pid_file ]
  then
    su $dendro_username touch $teamcity_pid_file
  else
    rm -f $teamcity_pid_file
  fi

  su $dendro_username \
    "cd $teamcity_installation_path/bin; /bin/bash -c "exec "$teamcity_installation_path/bin/teamcity-server.sh start" >> $teamcity_log_file 2>&1 & echo $! >> $teamcity_pid_file""
}

start() {
  while [ ! "$stopped" = "false" ]
  do
    echo "Monitoring TeamCity Server... PID: $pid"
    if [ "$pid" = "" ] || [ ! "$(kill -0 $pid)" ]
    then
      echo "ReStart of TeamCity Server..."
      start_service_command
      pid=$(cat $teamcity_pid_file)
      if [ ! "$pid" = "" ]
      then
          echo "Grepping PID: $pid"
          ps aux | grep $pid
      fi
    fi
    sleep 1
  done

  return 0
}

#usar pgrep em outros casos

stop() {
  stopped=true
  pid=$(cat $teamcity_pid_file)

  if [ ! "$(su $dendro_username -c "(cd $teamcity_installation_path && $teamcity_installation_path/bin/teamcity-server.sh stop >> $teamcity_log_file 2>&1 )")" ]
  then
    echo "Stopped TeamCity server."
  fi

  ### Now, delete the pid file ###
  rm -f $teamcity_pid_file
  return 0
}

case "$1" in
  start)
    echo "Starting TeamCity server..."
    start
    ;;
  stop)
    echo "Stopping TeamCity server..."
    stop
    ;;
  status)
    status $teamcity_service_name
    ;;
  restart)
    echo "Restarting TeamCity server..."
    stop && start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

# start() {
#   stopped="false"
#
#   cd $teamcity_installation_path; $teamcity_installation_path/bin/teamcity-server.sh start >> $teamcity_log_file 2>&1 &
#   pid=$!
#
#         echo "First Start of TeamCity Server...2"
#     echo "$pid"
#
#   echo "First Start of TeamCity Server..."
#
#   while [ "$stopped" = "false" ]
#   do
#     echo "First Start of TeamCity Server...1"
#     if [ ! "$(kill -0 $pid)" ]
#     then
#       echo "First Start of TeamCity Server...2"
#       su $dendro_username -c "(cd $teamcity_installation_path && $teamcity_installation_path/bin/teamcity-server.sh start >> $teamcity_log_file 2>&1 ) &"
#       pid=$!
#       #echo the pid of the service to the file
#       sudo echo $pid | tee $teamcity_pid_file
#     fi
#     sleep 1
